version: "3.8"

services:
  directus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - myvolume:/home/kalkidan/docker-folder
    image: directus
    container_name: derp-directus
    ports:
      - "8055:8055"
    env_file:
      - .env

volumes:
  myvolume: